version: "3"

services:
    server:
        container_name: server
        image: nginx:latest
        volumes:
            - ../docker-data/server/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www/html
        ports:
            - "127.0.0.1:80:80"
        depends_on:
            - translator
    translator:
        container_name: translator
        image: php-xdebug-composer-image
        working_dir: '/var/www/html'
        volumes:
            - ../docker-data/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
            - ../docker-data/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    database:
        container_name: database
        image: postgres
        restart: always
        volumes:
            - ./database/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=api_app
            - POSTGRES_PASSWORD=er54z4q9
            - POSTGRES_DB=guest_book
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "127.0.0.1:5432:5432"

